import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Shared/Navbar/Navbar";
import Footer from "@/Component/Shared/Footer/Footer";
import Provider from "./Lib/Provider";
import ToastPage from "./Toast/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="forest"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Provider>
          <div className="min-h-screen flex flex-col">
            <Navbar></Navbar>
            <main className="flex-1">
              {children}
            </main>
            <Footer></Footer>
            <ToastPage/>
          </div>
        </Provider>
      </body>
    </html>
  );
}
